# Generated by Django 5.2.3 on 2025-06-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageNumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='re_year',
            field=models.DateField(null=True),
        ),
    ]
